language: php
dist: xenial

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.monorepo-split-cache

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - COMPOSER_MEMORY_LIMIT=-1

jobs:
  include:
    - stage: test
      name: 'Test installing the split repos'
      php: 7.2
      script:
        - cd $TRAVIS_BUILD_DIR/calendar-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/core-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/faq-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/manager-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/news-bundle && run_split_tests

    - stage: test
      name: 'Test installing the lowest dependencies'
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
      script:
        - run_tests
        - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
        - php vendor/bin/monorepo-tools composer-json --validate

    - stage: test
      php: 7.1
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - run_tests
        - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
        - php vendor/bin/monorepo-tools composer-json --validate

    - stage: test
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - run_tests
        - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
        - php vendor/bin/monorepo-tools composer-json --validate

    # PHP-CS-Fixer is not yet compatible with PHP 7.3
    - stage: test
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --ignore-platform-reqs --no-interaction --no-suggest
      script:
        - phpdbg -qrr vendor/bin/phpunit -c calendar-bundle --coverage-clover=calendar-bundle.xml
        - phpdbg -qrr vendor/bin/phpunit -c core-bundle --testsuite=coverage --coverage-clover=core-bundle.xml
        - php vendor/bin/phpunit -c core-bundle --testsuite=functional
        - phpdbg -qrr vendor/bin/phpunit -c faq-bundle --coverage-clover=faq-bundle.xml
        - phpdbg -qrr vendor/bin/phpunit -c manager-bundle --coverage-clover=manager-bundle.xml
        - phpdbg -qrr vendor/bin/phpunit -c news-bundle --coverage-clover=news-bundle.xml
        - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
        - php vendor/bin/monorepo-tools composer-json --validate
      after_script:
        - php vendor/bin/php-coveralls -o coveralls-upload.json -x calendar-bundle.xml -x core-bundle.xml -x faq-bundle.xml -x manager-bundle.xml -x news-bundle.xml

    # Ignore the platform requirements for the upcoming PHP version
    - stage: test
      if: 'type = cron'
      php: 7.4snapshot
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --ignore-platform-reqs --no-interaction --no-suggest
      script:
        - run_tests
        - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
        - php vendor/bin/monorepo-tools composer-json --validate

    - stage: test
      if: 'type = cron'
      php: nightly
      install:
          - phpenv config-rm xdebug.ini || true
          - composer update --ignore-platform-reqs --no-interaction --no-suggest
      script:
          - run_tests
          - php vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress
          - php vendor/bin/monorepo-tools composer-json --validate

    # Split the monorepo
    - stage: split
      name: 'Split the monorepo'
      if: 'type = push AND (branch =~ /^(master|\d+\.\d+)$/ OR tag IS present)'
      php: 7.2
      before_install: true
      install:
        - phpenv config-rm xdebug.ini || true
        - rm composer.json
        - composer require contao/monorepo-tools:dev-master --no-interaction --no-suggest
      script:
        - php vendor/bin/monorepo-tools split $TRAVIS_BRANCH --cache-dir $HOME/.monorepo-split-cache

  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_install:
  - |
    # Helper functions
    run_tests () {
      local status=0
      php vendor/bin/phpunit -c calendar-bundle --colors=always || status=1
      php vendor/bin/phpunit -c core-bundle --colors=always || status=1
      php vendor/bin/phpunit -c core-bundle --testsuite=functional --colors=always || status=1
      php vendor/bin/phpunit -c faq-bundle --colors=always || status=1
      php vendor/bin/phpunit -c installation-bundle --colors=always || status=1
      php vendor/bin/phpunit -c manager-bundle --colors=always || status=1
      php vendor/bin/phpunit -c news-bundle --colors=always || status=1
      return $status
    }
    run_split_tests () {
      php -r '
        $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
        if ("contao/core-bundle" !== $data["name"]) {
          $data["repositories"][0]["type"] = "path";
          $data["repositories"][0]["url"] = "../core-bundle";
        }
        if ("contao/installation-bundle" !== $data["name"]) {
          $data["repositories"][1]["type"] = "path";
          $data["repositories"][1]["url"] = "../installation-bundle";
        }
        file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
      '
      composer update --no-interaction --no-suggest
      php vendor/bin/phpunit --colors=always
    }
  - mysql -e "CREATE database contao_test"
