language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.monorepo-split-cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'

jobs:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.1
    - php: 7.2

    # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

    # Generate the coverage with the latest PHP version
    - php: 7.2
      env: COVERAGE='--exclude-group contao3'

    # Lowest dependencies with the oldest and latest PHP versions
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

    # Split the monorepo
    - stage: split
      if: 'type = push AND branch =~ /^(master|\d+\.\d+)$/'
      php: 7.2
      install:
        # Project dependencies do not need to be installed for the split script
        - rm composer.json
        - composer require contao/monorepo-tools:dev-master --no-interaction --no-suggest
      script: vendor/bin/monorepo-tools split $TRAVIS_BRANCH --cache-dir $HOME/.monorepo-split-cache

  allow_failures:
    - php: nightly

before_install:
  - if [[ ! $COVERAGE ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  # To be removed when this is resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction --no-suggest; fi
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest

script:
  - |
    if [[ $COVERAGE ]]; then
      mkdir -p build/logs
      php vendor/bin/phpunit -c calendar-bundle $COVERAGE --coverage-clover build/logs/calendar-bundle.xml
      php vendor/bin/phpunit -c core-bundle $COVERAGE --coverage-clover build/logs/core-bundle.xml
      php vendor/bin/phpunit -c faq-bundle $COVERAGE --coverage-clover build/logs/faq-bundle.xml
      php vendor/bin/phpunit -c manager-bundle $COVERAGE --coverage-clover build/logs/manager-bundle.xml
      php vendor/bin/phpunit -c news-bundle $COVERAGE --coverage-clover build/logs/news-bundle.xml
    else
      php vendor/bin/phpunit -c calendar-bundle
      php vendor/bin/phpunit -c core-bundle
      php vendor/bin/phpunit -c faq-bundle
      php vendor/bin/phpunit -c installation-bundle
      php vendor/bin/phpunit -c manager-bundle
      php vendor/bin/phpunit -c news-bundle
    fi

  # Check whether the composer.json files of the bundles are in sync with the root one
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/monorepo-tools composer-json --validate; fi

after_script:
  - if [[ $COVERAGE ]]; then php vendor/bin/php-coveralls -x build/logs/calendar-bundle.xml -x build/logs/core-bundle.xml -x build/logs/faq-bundle.xml -x build/logs/manager-bundle.xml -x build/logs/news-bundle.xml; fi
