imports:
    - { resource: ../security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Framework configuration
framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing_prod.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    session:
        handler_id: ~
    csrf_protection: ~
    translator: { fallbacks: ["%locale%"] }

# Contao configuration
contao:
    prepend_locale: "%prepend_locale%"
    encryption_key: "%secret%"

# Twig configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                user:     "%database_user%"
                password: "%database_password%"
                dbname:   "%database_name%"
                charset:  UTF8

# SwiftMailer configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"

# Lexik configuration
lexik_maintenance:
    authorized:
        path: ^/contao($|/)
        attributes:
            _bypass_maintenance: true
    driver:
        class:   "Lexik\\Bundle\\MaintenanceBundle\\Drivers\\FileDriver"
        options: { file_path: "%kernel.root_dir%/cache/lock" }
