language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini

before_script:
  - composer selfupdate
  - travis_wait composer update $COMPOSER_FLAGS --no-interaction
  - phpenv config-add /tmp/xdebug.ini

script:
  - mkdir -p build/logs
  - php -d zend_extension=xdebug.so vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
