services:
    _defaults:
        autoconfigure: true

    contao.listener.administrator_email:
        class: Contao\CoreBundle\EventListener\AdministratorEmailListener
        arguments:
            - '@contao.framework'
            - '@translator'
            - '@router'
            - '@request_stack'
            - '@security.helper'

    contao.listener.backend_locale:
        class: Contao\CoreBundle\EventListener\BackendLocaleListener
        arguments:
            - '@security.helper'
            - '@translator'

    contao.listener.backend_noindex:
        class: Contao\CoreBundle\EventListener\BackendNoindexListener
        arguments:
            - '@contao.routing.scope_matcher'

    contao.listener.backend_preview_redirect:
        class: Contao\CoreBundle\EventListener\BackendPreviewRedirectListener
        arguments:
            - '@contao.routing.scope_matcher'

    contao.listener.backend_rebuild_cache_message:
        class: Contao\CoreBundle\EventListener\BackendRebuildCacheMessageListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@cache.system'
            - '@translator'

    contao.listener.clear_session_data:
        class: Contao\CoreBundle\EventListener\ClearSessionDataListener

    contao.listener.command_scheduler:
        class: Contao\CoreBundle\EventListener\CommandSchedulerListener
        arguments:
            - '@contao.cron'
            - '@database_connection'
            - '%fragment.path%'
            - ~

    contao.listener.csp_report:
        class: Contao\CoreBundle\EventListener\CspReportListener
        arguments:
            - '@logger'

    contao.listener.csrf_token_cookie:
        class: Contao\CoreBundle\EventListener\CsrfTokenCookieSubscriber
        arguments:
            - '@contao.csrf.token_manager'
            - '@contao.csrf.token_storage'
            - '%contao.csrf_cookie_prefix%'

    contao.listener.data_container.accordion:
        class: Contao\CoreBundle\EventListener\DataContainer\AccordionListener

    contao.listener.data_container.backend_favorites:
        class: Contao\CoreBundle\EventListener\DataContainer\BackendFavoritesListener
        arguments:
            - '@security.helper'
            - '@request_stack'

    contao.listener.data_container.content_composition:
        class: Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener
        public: true
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@contao.routing.page_registry'
            - '@database_connection'
            - '@request_stack'

    contao.listener.data_container.content_element_type:
        class: Contao\CoreBundle\EventListener\DataContainer\ContentElementTypeListener
        arguments:
            - '@security.helper'

    contao.listener.data_container.csp_save_callback:
        class: Contao\CoreBundle\EventListener\DataContainer\CspSaveCallbackListener
        arguments:
            - '@contao.csp.parser'

    contao.listener.data_container.cte_alias:
        class: Contao\CoreBundle\EventListener\DataContainer\CteAliasListener
        arguments:
            - '@request_stack'
            - '@security.helper'
            - '@database_connection'
            - '@contao.framework'

    contao.listener.data_container.default_global_operations:
        class: Contao\CoreBundle\EventListener\DataContainer\DefaultGlobalOperationsListener

    contao.listener.data_container.default_operations:
        class: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@database_connection'

    contao.listener.data_container.description_list_label:
        class: Contao\CoreBundle\EventListener\DataContainer\DescriptionListLabelListener
        public: true
        arguments:
            - '@translator'

    contao.listener.data_container.disable_app_configured_settings:
        class: Contao\CoreBundle\EventListener\DataContainer\DisableAppConfiguredSettingsListener
        arguments:
            - '@translator'
            - '@contao.framework'
            - '%contao.localconfig%'

    contao.listener.data_container.disable_canonical_fields:
        class: Contao\CoreBundle\EventListener\DataContainer\DisableCanonicalFieldsListener
        arguments:
            - '@contao.framework'
            - '@translator'

    contao.listener.data_container.enum_options:
        class: Contao\CoreBundle\EventListener\DataContainer\EnumOptionsListener
        arguments:
            - '@translator'

    contao.listener.data_container.frontend_module_permissions:
        class: Contao\CoreBundle\EventListener\DataContainer\FrontendModulePermissionsListener
        arguments:
            - '@security.helper'
            - '@database_connection'

    contao.listener.data_container.layout_options:
        class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
        arguments:
            - '@database_connection'

    contao.listener.data_container.legacy_gallery_palette:
        class: Contao\CoreBundle\EventListener\DataContainer\LegacyGalleryPaletteListener

    contao.listener.data_container.logout_page_redirect:
        class: Contao\CoreBundle\EventListener\DataContainer\LogoutPageRedirectListener

    contao.listener.data_container.member_groups:
        class: Contao\CoreBundle\EventListener\DataContainer\MemberGroupsListener
        arguments:
            - '@database_connection'
            - '@translator'

    contao.listener.data_container.page_routing:
        class: Contao\CoreBundle\EventListener\DataContainer\PageRoutingListener
        public: true
        arguments:
            - '@contao.framework'
            - '@contao.routing.page_registry'
            - '@twig'

    contao.listener.data_container.page_search:
        class: Contao\CoreBundle\EventListener\DataContainer\PageSearchListener
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'

    contao.listener.data_container.page_type_options:
        class: Contao\CoreBundle\EventListener\DataContainer\PageTypeOptionsListener
        public: true
        arguments:
            - '@contao.routing.page_registry'
            - '@security.helper'
            - '@?event_dispatcher'

    contao.listener.data_container.page_url:
        class: Contao\CoreBundle\EventListener\DataContainer\PageUrlListener
        public: true
        arguments:
            - '@contao.framework'
            - '@contao.slug'
            - '@translator'
            - '@database_connection'
            - '@contao.routing.page_registry'
            - '@router'
            - '@contao.routing.url_matcher'

    contao.listener.data_container.page_use_ssl_default:
        class: Contao\CoreBundle\EventListener\DataContainer\PageUseSslDefaultListener
        arguments:
            - '@request_stack'

    contao.listener.data_container.personal_data_password:
        class: Contao\CoreBundle\EventListener\DataContainer\PersonalDataPasswordListener
        arguments:
            - '@database_connection'
            - '@translator'
            - '@security.helper'

    contao.listener.data_container.preview_link:
        class: Contao\CoreBundle\EventListener\DataContainer\PreviewLinkListener
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@security.helper'
            - '@request_stack'
            - '@translator'
            - '@router'
            - '@uri_signer'
            - '%contao.preview_script%'

    contao.listener.data_container.record_preview:
        class: Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener
        arguments:
            - '@contao.framework'
            - '@database_connection'

    contao.listener.data_container.reset_custom_template:
        class: Contao\CoreBundle\EventListener\DataContainer\ResetCustomTemplateListener
        arguments:
            - '@database_connection'

    contao.listener.data_container.start_stop_validation:
        class: Contao\CoreBundle\EventListener\DataContainer\StartStopValidationListener
        arguments:
            - '@translator'

    contao.listener.data_container.template_options:
        class: Contao\CoreBundle\EventListener\DataContainer\TemplateOptionsListener
        arguments:
            - '@contao.twig.finder_factory'
            - '@database_connection'
            - '@contao.framework'
            - '@request_stack'
            - '@contao.twig.filesystem_loader'

    contao.listener.data_container.theme_operations:
        class: Contao\CoreBundle\EventListener\DataContainer\ThemeOperationsListener
        arguments:
            - '@security.helper'

    contao.listener.data_container.theme_templates:
        class: Contao\CoreBundle\EventListener\DataContainer\ThemeTemplatesListener
        arguments:
            - '@contao.twig.filesystem_loader'
            - '@contao.twig.loader.theme_namespace'
            - '@translator'

    contao.listener.data_container.undo.jump_to_parent_operation:
        class: Contao\CoreBundle\EventListener\DataContainer\Undo\JumpToParentOperationListener
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@translator'
            - '@security.helper'

    contao.listener.data_container.undo.label:
        class: Contao\CoreBundle\EventListener\DataContainer\Undo\LabelListener
        arguments:
            - '@contao.framework'
            - '@twig'

    contao.listener.data_container.undo_operation:
        class: Contao\CoreBundle\EventListener\DataContainer\Undo\UndoOperationListener
        arguments:
            - '@security.helper'

    contao.listener.data_container.user_admin_field:
        class: Contao\CoreBundle\EventListener\DataContainer\UserAdminFieldListener
        arguments:
            - '@security.helper'

    contao.listener.data_container.validate_custom_rgxp:
        class: Contao\CoreBundle\EventListener\DataContainer\ValidateCustomRgxpListener
        arguments:
            - '@translator'

    contao.listener.data_container_callback:
        class: Contao\CoreBundle\EventListener\DataContainerCallbackListener

    contao.listener.dbafs_metadata:
        class: Contao\CoreBundle\EventListener\DbafsMetadataSubscriber
        arguments:
            - '@request_stack'

    contao.listener.doctrine_schema:
        class: Contao\CoreBundle\EventListener\DoctrineSchemaListener
        arguments:
            - '@contao.doctrine.dca_schema_provider'
            - '@messenger.receiver_locator'

    contao.listener.exception_converter:
        class: Contao\CoreBundle\EventListener\ExceptionConverterListener

    contao.listener.image_size_options:
        class: Contao\CoreBundle\EventListener\ImageSizeOptionsListener
        arguments:
            - '@security.helper'
            - '@contao.image.sizes'

    contao.listener.insecure_installation:
        class: Contao\CoreBundle\EventListener\InsecureInstallationListener
        arguments:
            - '%kernel.secret%'
            - '%contao.web_dir%'

    contao.listener.insert_tags.asset:
        class: Contao\CoreBundle\EventListener\InsertTags\AssetListener
        arguments:
            - '@assets.packages'

    contao.listener.insert_tags.date:
        class: Contao\CoreBundle\EventListener\InsertTags\DateListener
        arguments:
            - '@contao.framework'
            - '@request_stack'

    contao.listener.insert_tags.translation:
        class: Contao\CoreBundle\EventListener\InsertTags\TranslationListener
        arguments:
            - '@translator'

    contao.listener.json_ld_schema:
        class: Contao\CoreBundle\EventListener\ContaoJsonLdSchemaListener

    contao.listener.locale:
        class: Contao\CoreBundle\EventListener\LocaleSubscriber
        arguments:
            - '@translator'
            - '@contao.routing.scope_matcher'
            - '@contao.intl.locales'

    contao.listener.make_response_private:
        class: Contao\CoreBundle\EventListener\MakeResponsePrivateListener
        arguments:
            - '@contao.routing.scope_matcher'

    contao.listener.menu.backend:
        class: Contao\CoreBundle\EventListener\Menu\BackendMenuListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@request_stack'
            - '@translator'
            - '@contao.framework'

    contao.listener.menu.backend_favorites:
        class: Contao\CoreBundle\EventListener\Menu\BackendFavoritesListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@request_stack'
            - '@database_connection'
            - '@translator'
            - '@contao.csrf.token_manager'

    contao.listener.menu.backend_logout:
        class: Contao\CoreBundle\EventListener\Menu\BackendLogoutListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@security.logout_url_generator'
            - '@translator'

    contao.listener.menu.backend_preview:
        class: Contao\CoreBundle\EventListener\Menu\BackendPreviewListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@request_stack'
            - '@translator'
            - '@event_dispatcher'

    contao.listener.merge_http_headers:
        class: Contao\CoreBundle\EventListener\MergeHttpHeadersListener
        arguments:
            - '@contao.framework'

    contao.listener.page_access:
        class: Contao\CoreBundle\EventListener\PageAccessListener
        arguments:
            - '@contao.framework'
            - '@security.helper'

    contao.listener.page_trail_cache_tags:
        class: Contao\CoreBundle\EventListener\PageTrailCacheTagsListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@?fos_http_cache.http.symfony_response_tagger'

    contao.listener.pretty_error_screen:
        class: Contao\CoreBundle\EventListener\PrettyErrorScreenListener
        arguments:
            - '%contao.pretty_error_screens%'
            - '@twig'
            - '@contao.framework'
            - '@security.helper'
            - '@contao.routing.page_registry'
            - '@http_kernel'
            - '@contao.routing.page_finder'

    contao.listener.preview_authentication:
        class: Contao\CoreBundle\EventListener\PreviewAuthenticationListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.security.token_checker'
            - '@router'
            - '@uri_signer'

    contao.listener.preview_toolbar:
        class: Contao\CoreBundle\EventListener\PreviewToolbarListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.security.token_checker'
            - '@twig'
            - '@router'
            - '@contao.routing.response_context.csp_handler_factory'
            - '%contao.preview_script%'

    contao.listener.preview_url_convert:
        class: Contao\CoreBundle\EventListener\PreviewUrlConvertListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.page_registry'
            - '@contao.routing.content_url_generator'
            - '@uri_signer'
            - '%fragment.path%'

    contao.listener.preview_url_create:
        class: Contao\CoreBundle\EventListener\PreviewUrlCreateListener
        arguments:
            - '@contao.framework'

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - '@contao.token_generator'
            - '@contao.routing.scope_matcher'

    contao.listener.request_token:
        class: Contao\CoreBundle\EventListener\RequestTokenListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
            - '%contao.csrf_cookie_prefix%'

    contao.listener.response_exception:
        class: Contao\CoreBundle\EventListener\ResponseExceptionListener

    contao.listener.robots_txt:
        class: Contao\CoreBundle\EventListener\RobotsTxtListener
        arguments:
            - '@contao.framework'
            - '@?web_profiler.debug_toolbar'
            - '%contao.backend.route_prefix%'

    contao.listener.search_index:
        class: Contao\CoreBundle\EventListener\SearchIndexListener
        arguments:
            - '@messenger.bus.default'
            - '%fragment.path%'

    contao.listener.security.logout:
        class: Contao\CoreBundle\EventListener\Security\LogoutListener
        arguments:
            - '@security.http_utils'
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '@logger'

    contao.listener.security.switch_user:
        class: Contao\CoreBundle\EventListener\Security\SwitchUserListener
        arguments:
            - '@security.token_storage'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: contao.access }

    contao.listener.security.two_factor_frontend:
        class: Contao\CoreBundle\EventListener\Security\TwoFactorFrontendListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@contao.routing.page_finder'
            - '@contao.routing.content_url_generator'
            - '@security.token_storage'
            - '%scheb_two_factor.security_tokens%'

    contao.listener.service_unavailable:
        class: Contao\CoreBundle\EventListener\ServiceUnavailableListener
        arguments:
            - '@contao.routing.scope_matcher'

    contao.listener.store_referer:
        class: Contao\CoreBundle\EventListener\StoreRefererListener
        arguments:
            - '@security.helper'
            - '@contao.routing.scope_matcher'

    contao.listener.subrequest_cache:
        class: Contao\CoreBundle\EventListener\SubrequestCacheSubscriber

    contao.listener.transport_security_header:
        class: Contao\CoreBundle\EventListener\TransportSecurityHeaderListener
        arguments:
            - '@contao.routing.scope_matcher'

    contao.listener.unwrap_twig_exception:
        class: Contao\CoreBundle\EventListener\UnwrapTwigExceptionListener

    contao.listener.user_session:
        class: Contao\CoreBundle\EventListener\UserSessionListener
        arguments:
            - '@database_connection'
            - '@security.helper'
            - '@contao.routing.scope_matcher'
            - '@event_dispatcher'

    contao.listener.widget.custom_rgxp:
        class: Contao\CoreBundle\EventListener\Widget\CustomRgxpListener
        arguments:
            - '@translator'

    contao.listener.widget.http_url:
        class: Contao\CoreBundle\EventListener\Widget\HttpUrlListener
        arguments:
            - '@translator'

    contao.listener.widget.root_page_dependent_select:
        class: Contao\CoreBundle\EventListener\Widget\RootPageDependentSelectListener
        arguments:
            - '@database_connection'
            - '@router'
            - '@translator'

    contao.messenger.message_listener:
        class: Contao\CoreBundle\Messenger\EventListener\MessageListener
        arguments:
            - '@monolog.logger.contao.error'

    contao.twig.loader.auto_refresh_template_hierarchy_listener:
        class: Contao\CoreBundle\Twig\Loader\AutoRefreshTemplateHierarchyListener
        arguments:
            - '@contao.twig.filesystem_loader'
            - '%kernel.environment%'
