services:
    contao_newsletter.cron.purge_subscriptions:
        class: Contao\NewsletterBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'

    contao_newsletter.listener.member_activation_mail:
        class: Contao\NewsletterBundle\EventListener\MemberActivationMailListener
        arguments:
            - '@database_connection'
        tags:
            - kernel.event_listener

    contao_newsletter.listener.sitemap:
        class: Contao\NewsletterBundle\EventListener\SitemapListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_newsletter.security.newsletter_channel_access_voter:
        class: Contao\NewsletterBundle\Security\Voter\NewsletterChannelAccessVoter
        arguments:
            - '@security.helper'
