##
# Listener priorities
#
# The priorities of the following listeners must be lower than the one of the
# Symfony route listener (defaults to 32).
#
# - 30: ContainerScopeListener
# - 28: RefererIdListener
# - 26: InitializeSystemListener
# - 24: ToggleViewListener
# - 22: OutputFromCacheListener
#
# Session listener
#
# The priority of the session listener must be higher than the other listeners but
# lower than the one of the Symfony session listener (defaults to 128).
#
# - 64: SessionListener
#
# Exception listener
#
# The priority of the exception listeners must be higher than the one of the
# Twig exception listener (defaults to 0).
#
# - 64: ExceptionConverterListener
# - 32: PrettyErrorScreensListener
#
# Do not change the priorities unless you know what you are doing!
##
services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.exception_converter:
        class: Contao\CoreBundle\EventListener\ExceptionConverterListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 64 }

    contao.listener.initialize_system:
        class: Contao\CoreBundle\EventListener\InitializeSystemListener
        arguments:
            - "@router"
            - "@session"
            - "%kernel.root_dir%"
            - "@security.csrf.token_manager"
            - "%contao.csrf_token_name%"
            - "@contao.adapter.config"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 26 }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 22 }

    contao.listener.pretty_error_screens:
        class: Contao\CoreBundle\EventListener\PrettyErrorScreenListener
        arguments:
            - "%contao.pretty_error_screens%"
            - "@templating"
            - "@contao.adapter.config"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 32 }

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - "@contao.referer_id.manager"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 28 }

    contao.listener.response_exception:
        class: Contao\CoreBundle\EventListener\ResponseExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    contao.listener.session:
        class: Contao\CoreBundle\EventListener\SessionListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: registerContaoAttributeBags, priority: 64 }
            - { name: kernel.event_listener, event: console.command, method: registerContaoAttributeBags, priority: 64 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 24 }

    contao.listener.user_session:
        class: Contao\CoreBundle\EventListener\UserSessionListener
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            - '@session'
            - '@doctrine.dbal.default_connection'
            - '@security.token_storage'
        tags:
            # Priority must be lower than contao.listener.session (64)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            # Priority must be higher than the framework bundle save session listener (-1000)
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

