services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [setContainer, ['@service_container']]

    Contao\CoreBundle\EventListener\DataContainer\ResetCustomTemplateListener:
        arguments:
            - '@database_connection'

    Contao\CoreBundle\EventListener\PreviewUrlCreateListener:
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao.listener.backend_locale:
        class: Contao\CoreBundle\EventListener\BackendLocaleListener
        arguments:
            - '@security.helper'
            - '@translator'
        tags:
            # The priority must be lower than the one of the firewall listener (defaults to 8)
            - { name: kernel.event_listener, priority: 7 }

    Contao\CoreBundle\EventListener\BackendPreviewRedirectListener:
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - kernel.event_listener

    contao.listener.menu.backend_menu:
        class: Contao\CoreBundle\EventListener\Menu\BackendMenuListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@request_stack'
            - '@translator'
            - '@contao.framework'
        tags:
            # Make sure this listener comes before the other ones adding to its tree
            - { name: kernel.event_listener, priority: 10 }

    contao.listener.menu.backend_logout:
        class: Contao\CoreBundle\EventListener\Menu\BackendLogoutListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@security.logout_url_generator'
            - '@translator'
        tags:
            - kernel.event_listener

    contao.listener.menu.backend_preview:
        class: Contao\CoreBundle\EventListener\Menu\BackendPreviewListener
        arguments:
            - '@security.helper'
            - '@router'
            - '@request_stack'
            - '@translator'
            - '@event_dispatcher'
        tags:
            - kernel.event_listener

    contao.listener.bypass_maintenance:
        class: Contao\CoreBundle\EventListener\BypassMaintenanceListener
        arguments:
            - '@contao.security.token_checker'
        tags:
            # The priority must be higher than the one of the Lexik maintenance bundle (defaults to 0)
            - { name: kernel.event_listener, priority: 6 }

    contao.listener.clear_session_data:
        class: Contao\CoreBundle\EventListener\ClearSessionDataListener
        tags:
            # The priority must be higher than the one of the Symfony save session listener (defaults to -1000)
            - { name: kernel.event_listener, priority: -768 }

    contao.listener.command_scheduler:
        class: Contao\CoreBundle\EventListener\CommandSchedulerListener
        arguments:
            - '@Psr\Container\ContainerInterface'
            - '@contao.framework'
            - '@database_connection'
            - '%fragment.path%'
        tags:
            - kernel.event_listener

    contao.listener.csrf_token_cookie:
        class: Contao\CoreBundle\EventListener\CsrfTokenCookieSubscriber
        arguments:
            - '@contao.csrf.token_manager'
            - '@contao.csrf.token_storage'
            - '%contao.csrf_cookie_prefix%'
        tags:
            - kernel.event_subscriber

    contao.listener.data_container_callback:
        class: Contao\CoreBundle\EventListener\DataContainerCallbackListener
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    contao.listener.element_template_options:
        class: Contao\CoreBundle\EventListener\DataContainer\TemplateOptionsListener
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - ce_
            - Contao\ContentProxy
        tags:
            - { name: contao.callback, table: tl_content, target: fields.customTpl.options }

    Contao\CoreBundle\EventListener\InterestCohortListener:
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - kernel.event_listener

    contao.listener.module_template_options:
        class: Contao\CoreBundle\EventListener\DataContainer\TemplateOptionsListener
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - mod_
            - Contao\ModuleProxy
        tags:
            - { name: contao.callback, table: tl_module, target: fields.customTpl.options }

    contao.listener.doctrine_schema:
        class: Contao\CoreBundle\EventListener\DoctrineSchemaListener
        arguments:
            - '@contao.doctrine.schema_provider'
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }

    contao.listener.doctrine_schema.adjust_search_url_length:
        class: Contao\CoreBundle\EventListener\DoctrineSchema\AdjustSearchUrlLengthListener
        arguments:
            - '@database_connection'
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema, priority: -100 }

    contao.listener.exception_converter:
        class: Contao\CoreBundle\EventListener\ExceptionConverterListener
        tags:
            # The priority must be higher than the one of the response exception listener (defaults to 64)
            - { name: kernel.event_listener, priority: 96 }

    contao.listener.initialize_controller:
        class: Contao\CoreBundle\EventListener\InitializeControllerListener
        tags:
            - { name: kernel.event_listener, priority: 1000 }

    contao.listener.insecure_installation:
        class: Contao\CoreBundle\EventListener\InsecureInstallationListener
        tags:
            - kernel.event_listener

    contao.listener.insert_tags.asset:
        class: Contao\CoreBundle\EventListener\InsertTags\AssetListener
        arguments:
            - '@assets.packages'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao.listener.insert_tags.translation:
        class: Contao\CoreBundle\EventListener\InsertTags\TranslationListener
        arguments:
            - '@translator'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao.listener.legacy_login_constants:
        class: Contao\CoreBundle\EventListener\LegacyLoginConstantsListener
        arguments:
            - '@contao.framework'
        tags:
            # The priority must be lower than the one of the firewall listener (defaults to 8)
            - { name: kernel.event_listener, priority: 7 }

    contao.listener.locale:
        class: Contao\CoreBundle\EventListener\LocaleSubscriber
        arguments:
            - '@translator'
            - '@contao.routing.scope_matcher'
            - '%contao.locales%'
        tags:
            - kernel.event_subscriber

    contao.listener.make_response_private:
        class: Contao\CoreBundle\EventListener\MakeResponsePrivateListener
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            # The priority must be lower than the one of MergeHttpHeadersListener (defaults to 256)
            # and must be lower than the one of the ClearSessionDataListener listener (defaults to -768)
            # and must be lower than the one of the CsrfTokenCookieSubscriber listener (defaults to -832)
            - { name: kernel.event_listener, priority: -896 }

    contao.listener.merge_http_headers:
        class: Contao\CoreBundle\EventListener\MergeHttpHeadersListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, priority: 256 }
            - { name: kernel.reset, method: reset }

    contao.listener.page_trail_cache_tags:
        class: Contao\CoreBundle\EventListener\PageTrailCacheTagsListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@?fos_http_cache.http.symfony_response_tagger'
        tags:
            - { name: kernel.event_listener }

    contao.listener.pretty_error_screens:
        class: Contao\CoreBundle\EventListener\PrettyErrorScreenListener
        arguments:
            - '%contao.pretty_error_screens%'
            - '@twig'
            - '@contao.framework'
            - '@security.helper'
        tags:
            # The priority must be higher than the one of the Twig exception listener (defaults to -128)
            - { name: kernel.event_listener, priority: -96 }

    contao.listener.preview_bar:
        class: Contao\CoreBundle\EventListener\PreviewToolbarListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@twig'
            - '@router'
        tags:
            - kernel.event_listener

    contao.listener.preview_url_convert:
        class: Contao\CoreBundle\EventListener\PreviewUrlConvertListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao.listener.preview_authentication:
        class: Contao\CoreBundle\EventListener\PreviewAuthenticationListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.security.token_checker'
            - '@router'
            - '@uri_signer'
        tags:
            # The priority must be lower than the one of the firewall listener (defaults to 8)
            - { name: kernel.event_listener, priority: 7 }

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - '@contao.token_generator'
            - '@contao.routing.scope_matcher'
        tags:
            # The priority must be lower than the one of the Symfony route listener (defaults to 32)
            - { name: kernel.event_listener, priority: 20 }

    contao.listener.request_token:
        class: Contao\CoreBundle\EventListener\RequestTokenListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@Contao\CoreBundle\Csrf\ContaoCsrfTokenManager'
            - '%contao.csrf_token_name%'
            - '%contao.csrf_cookie_prefix%'
        tags:
            # The priority must be lower than the one of the Symfony route listener (defaults to 32)
            # and the Symfony locale aware listener (defaults to 15)
            - { name: kernel.event_listener, priority: 14 }

    contao.listener.response_exception:
        class: Contao\CoreBundle\EventListener\ResponseExceptionListener
        tags:
            - { name: kernel.event_listener, priority: 64 }

    contao.listener.robots_txt:
        class: Contao\CoreBundle\EventListener\RobotsTxtListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao.listener.search_index:
        class: Contao\CoreBundle\EventListener\SearchIndexListener
        arguments:
            - '@contao.search.indexer'
            - '%fragment.path%'
        tags:
            - kernel.event_listener

    contao.listener.store_referer:
        class: Contao\CoreBundle\EventListener\StoreRefererListener
        arguments:
            - '@security.helper'
            - '@contao.routing.scope_matcher'
        tags:
            - kernel.event_listener

    contao.listener.subrequest_cache:
        class: Contao\CoreBundle\EventListener\SubrequestCacheSubscriber
        tags:
            - kernel.event_subscriber
            - { name: kernel.reset, method: reset }

    contao.listener.switch_user:
        class: Contao\CoreBundle\EventListener\SwitchUserListener
        arguments:
            - '@security.token_storage'
            - '@logger'
        tags:
            - kernel.event_listener

    contao.listener.toggle_nodes_label:
        class: Contao\CoreBundle\EventListener\DataContainer\ToggleNodesLabelListener
        arguments:
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    contao.listener.two_factor.frontend:
        class: Contao\CoreBundle\EventListener\TwoFactorFrontendListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@security.token_storage'
            - '%scheb_two_factor.security_tokens%'
        tags:
            - kernel.event_listener

    contao.listener.user_session:
        class: Contao\CoreBundle\EventListener\UserSessionListener
        arguments:
            - '@database_connection'
            - '@security.helper'
            - '@contao.routing.scope_matcher'
            - '@event_dispatcher'
        tags:
            - kernel.event_listener
