name: PR

on:
    pull_request_target:
        types: [opened]

permissions:
    issues: write
    pull-requests: write

jobs:
    assign-pr:
        name: Assign
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Assign the author
              uses: toshimaru/auto-author-assign@v1.4.0

            - name: Assign the milestone
              uses: zoispag/action-assign-milestone@v1
              with:
                  milestone: 4.13
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Add the label
              uses: christianvuerings/add-labels@v1
              if: join(github.event.pull_request.labels) == ''
              with:
                  labels: bug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
