name: CI

on:
    pull_request: ~
    push:
        branches:
            - 4.9
        tags:
            - 4.9.*
    schedule:
        - cron: 0 13 * * MON,TUE

permissions: read-all

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        if: github.event_name != 'schedule'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: pcov

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Generate the coverage report
              run: php -d pcov.enabled=1 vendor/bin/phpunit --testsuite=coverage --coverage-clover=clover.xml --colors=always

            - name: Upload the coverage report
              uses: codecov/codecov-action@v3
              with:
                  files: ./clover.xml
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}

    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4 # Keep running this with PHP 7, otherwise there will be PHP 8 CS fixes
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin ecs install --no-interaction --no-progress
                  composer bin phpstan install --no-interaction --no-progress

            - name: Check the coding standard
              run: |
                  tools/ecs/vendor/bin/ecs check *-bundle/bin *-bundle/src *-bundle/tests --config tools/ecs/vendor/contao/easy-coding-standard/config/default.php --no-progress-bar --ansi
                  tools/ecs/vendor/bin/ecs check *-bundle/src/Resources/contao --config tools/ecs/vendor/contao/easy-coding-standard/config/legacy.php --no-progress-bar --ansi
                  tools/ecs/vendor/bin/ecs check *-bundle/src/Resources/contao/templates --config tools/ecs/vendor/contao/easy-coding-standard/config/template.php --no-progress-bar --ansi

            - name: Analyze the PHP files
              run: tools/phpstan/vendor/bin/phpstan analyse core-bundle/src core-bundle/tests --level=3 --no-progress

            - name: Analyze the YAML files
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install --upgrade setuptools wheel
                  python3 -m pip install --upgrade yamllint
                  /home/runner/.local/bin/yamllint .

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4, 8.0, 8.1]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

    nightly:
        name: PHP 8.2
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: composer install --ignore-platform-req=php --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

    prefer-lowest:
        name: Prefer Lowest
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: composer update --prefer-lowest --prefer-stable --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

    bundles:
        name: Bundles
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  tools: flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1

            - name: Test the single bundles
              run: |
                  bundles=(calendar-bundle core-bundle faq-bundle manager-bundle news-bundle)
                  for bundle in "${bundles[@]}"; do
                      cd $bundle
                      php -r '
                          $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
                          if ("contao/core-bundle" !== $data["name"]) {
                              $data["repositories"][0]["type"] = "path";
                              $data["repositories"][0]["url"] = "../core-bundle";
                          }
                          if ("contao/installation-bundle" !== $data["name"]) {
                              $data["repositories"][1]["type"] = "path";
                              $data["repositories"][1]["url"] = "../installation-bundle";
                          }
                          if ("contao/test-case" !== $data["name"]) {
                              $data["repositories"][2]["type"] = "path";
                              $data["repositories"][2]["url"] = "../test-case";
                          }
                          file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
                      '
                      COMPOSER_ROOT_VERSION=dev-${{ env.GITHUB_SHA }} composer install --no-interaction --no-progress
                      vendor/bin/phpunit --colors=always
                      cd ..
                  done

    windows:
        name: Windows
        runs-on: windows-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  ini-values: memory_limit=1G
                  tools: flex
                  coverage: none

            - name: Adjust the Git autocrlf setting
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit.bat --colors=always

    composer:
        name: Composer
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: json, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin monorepo install --no-interaction --no-progress

            - name: Validate the composer.json files
              run: tools/monorepo/vendor/bin/monorepo-tools composer-json --validate --ansi

    monorepo-split:
        name: Monorepo Split
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: json, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v1

            - name: Cache the monorepo split
              uses: actions/cache@v1
              with:
                  path: .monorepo-split-cache
                  key: dev-${GITHUB_REF##*/}

            - name: Install the dependencies
              run: composer global require contao/monorepo-tools:dev-main

            - name: Split the monorepo
              run: $HOME/.composer/vendor/bin/monorepo-tools split ${GITHUB_REF##*/}
              env:
                  GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
