name: CI

on:
    pull_request: ~
    schedule:
        - cron: 0 13 * * MON,THU

permissions: read-all

jobs:
    rector:
        name: Rector
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin rector install --no-interaction --no-progress

            - name: Run Rector
              run: tools/rector/vendor/bin/rector --config tools/rector/config/rector.php --dry-run --no-progress-bar

    ecs:
        name: ECS
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin ecs install --no-interaction --no-progress

            - name: Run ECS
              run: tools/ecs/vendor/bin/ecs check */bin */src */tests tools/*/bin tools/*/config tools/*/src --config tools/ecs/config/default.php --no-progress-bar --ansi

    ecs-legacy:
        name: ECS legacy
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin ecs install --no-interaction --no-progress

            - name: Run ECS
              run: |
                  tools/ecs/vendor/bin/ecs check *-bundle/contao --config tools/ecs/config/legacy.php --no-progress-bar --ansi
                  tools/ecs/vendor/bin/ecs check *-bundle/contao/templates --config tools/ecs/config/template.php --no-progress-bar --ansi

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin phpstan install --no-interaction --no-progress

            - name: Run PHPStan
              run: tools/phpstan/vendor/bin/phpstan analyse --no-progress

    yamllint:
        name: YAMLlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run YAMLlint
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install --upgrade setuptools wheel
                  python3 -m pip install --upgrade yamllint
                  /home/runner/.local/bin/yamllint .

    service-linter:
        name: Service linter
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin service-linter install --no-interaction --no-progress

            - name: Run the service linter
              run: tools/service-linter/bin/lint-service-ids --ansi

    require-checker:
        name: Require checker
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer -dcore-bundle install --no-interaction --no-progress
                  composer bin require-checker install --no-interaction --no-progress

            - name: Check for unknown symbols (contao/contao)
              run: tools/require-checker/vendor/bin/composer-require-checker check --config-file=tools/require-checker/config/config.json composer.json --ansi

            - name: Check for unknown symbols (contao/core-bundle)
              run: tools/require-checker/vendor/bin/composer-require-checker check --config-file=tools/require-checker/config/config.json core-bundle/composer.json --ansi

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests with PDO MySQL
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

            - name: Run the functional tests with MySQLi
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysqli://root:root@127.0.0.1:3306/contao_test

    reverse:
        name: PHP 8.1 reverse order
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests in reverse order
              run: vendor/bin/phpunit --order-by=reverse --extensions Contao\\CoreBundle\\Tests\\PhpunitExtension\\GlobalStateWatcher --colors=always

    nightly:
        name: PHP 8.3
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --ignore-platform-req=php+ --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

    prefer-lowest:
        name: Prefer lowest
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer update --prefer-lowest --prefer-stable --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

            - name: Run the functional tests with PDO MySQL
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test

            - name: Run the functional tests with MySQLi
              run: vendor/bin/phpunit --testsuite=functional --colors=always
              env:
                  DATABASE_URL: mysqli://root:root@127.0.0.1:3306/contao_test

    bundles:
        name: Bundles
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Test the single bundles
              run: |
                  bundles=(calendar-bundle comments-bundle core-bundle faq-bundle maker-bundle manager-bundle news-bundle newsletter-bundle)
                  for bundle in "${bundles[@]}"; do
                      cd $bundle
                      php -r '
                          $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
                          if ("contao/core-bundle" !== $data["name"]) {
                              $data["repositories"][0]["type"] = "path";
                              $data["repositories"][0]["url"] = "../core-bundle";
                          }
                          if ("contao/news-bundle" !== $data["name"]) {
                              $data["repositories"][1]["type"] = "path";
                              $data["repositories"][1]["url"] = "../news-bundle";
                          }
                          if ("contao/test-case" !== $data["name"]) {
                              $data["repositories"][2]["type"] = "path";
                              $data["repositories"][2]["url"] = "../test-case";
                          }
                          file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
                      '
                      COMPOSER_ROOT_VERSION=dev-${{ env.GITHUB_SHA }} composer install --no-interaction --no-progress
                      vendor/bin/phpunit --colors=always
                      cd ..
                  done

    dependencies:
        name: Dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: json, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin monorepo install --no-interaction --no-progress

            - name: Validate the composer.json files
              run: tools/monorepo/vendor/bin/monorepo-tools composer-json --validate --ansi

    # FIXME: remove again
    cypress:
        name: Cypress
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database contao_test"

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Symfony CLI
              run: |
                  wget https://get.symfony.com/cli/installer -O - | bash
                  mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  npm update
                  composer install --working-dir=cypress/webspace --no-interaction --no-progress
                  symfony server:ca:install

            - name: Run the Cypress tests
              id: cypress
              run: |
                  symfony server:start --port=8765 --dir=cypress/webspace --daemon
                  npx cypress run --config-file cypress/cypress.config.js
                  symfony server:stop --dir=cypress/webspace
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/contao_test
                  TERM: xterm-256color

            - name: Upload videos
              uses: actions/upload-artifact@v2
              if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
              with:
                  name: Cypress videos
                  path: tools/cypress/videos
                  retention-days: 14
