name: Windows

on:
    workflow_dispatch: ~
    schedule:
        - cron: 0 13 * * 1-5

permissions: read-all

jobs:
    windows:
        name: Contao ${{ matrix.contao }}
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                contao: [5.3, 5.6, 5.x]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, sodium, zlib
                  ini-values: memory_limit=1G
                  coverage: none

            - name: Adjust the Git autocrlf setting
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ matrix.contao }}
                  show-progress: false

            - name: Install Contao
              uses: ramsey/composer-install@v3

            - name: Run the unit tests
              run: vendor/bin/phpunit.bat
